var xml = '\
<?xml version="1.0" encoding="UTF-8" standalone="no"?>\
<!DOCTYPE score-partwise PUBLIC\
    "-//Recordare//DTD MusicXML 3.0 Partwise//EN"\
    "http://www.musicxml.com/dtds/partwise.dtd">\
<score-partwise version="3.0">\
	<part-list>\
		<score-part id="P1">\
			<part-name>Music</part-name>\
		</score-part>\
	</part-list>\
	<part id="P0">\
		<measure number="1">\
			<attributes>\
				<divisions>1</divisions>\
				<key>\
					<fifths>0</fifths>\
				</key>\
				<time>\
					<beats>4</beats>\
					<beat-type>4</beat-type>\
				</time>\
				<clef>\
					<sign>G</sign>\
					<line>2</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>2</duration>\
				<type>half</type>\
			</note>\
			<note>\
				<pitch>\
					<step>D</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>2</duration>\
				<type>half</type>\
			</note>\
		</measure>\
		<measure number="2">\
			<note>\
				<pitch>\
					<step>E</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>1</duration>\
				<type>quarter</type>\
			</note>\
			<note>\
				<pitch>\
					<step>F</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>.5</duration>\
				<type>eighth</type>\
			</note>\
			<note>\
				<pitch>\
					<step>G</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>.5</duration>\
				<type>eighth</type>\
			</note>\
			<note>\
				<pitch>\
					<step>A</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>.5</duration>\
				<type>eighth</type>\
			</note>\
			<note>\
				<pitch>\
					<step>B</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>.5</duration>\
				<type>eighth</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>.5</duration>\
				<type>eighth</type>\
			</note>\
		</measure>\
	</part>\
	<!--\
=========================================================\
-->\
	<part id="P1">\
		<measure number="1">\
			<attributes>\
				<divisions>1</divisions>\
				<key>\
					<fifths>0</fifths>\
					<mode>major</mode>\
				</key>\
				<time symbol="common">\
					<beats>4</beats>\
					<beat-type>4</beat-type>\
				</time>\
				<clef>\
					<sign>G</sign>\
					<line>2</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>quarter</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="2">\
			<attributes>\
				<clef>\
					<sign>C</sign>\
					<line>3</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>quarter</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="3">\
			<attributes>\
				<clef>\
					<sign>C</sign>\
					<line>4</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="4">\
			<attributes>\
				<clef>\
					<sign>F</sign>\
					<line>4</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="5">\
			<attributes>\
				<clef>\
					<sign>percussion</sign>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="6">\
			<attributes>\
				<clef>\
					<sign>G</sign>\
					<line>2</line>\
					<clef-octave-change>-1</clef-octave-change>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="7">\
			<attributes>\
				<clef>\
					<sign>F</sign>\
					<line>4</line>\
					<clef-octave-change>-1</clef-octave-change>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="8">\
			<attributes>\
				<clef>\
					<sign>F</sign>\
					<line>3</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="9">\
			<attributes>\
				<clef>\
					<sign>G</sign>\
					<line>1</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="10">\
			<attributes>\
				<clef>\
					<sign>C</sign>\
					<line>5</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="11">\
			<attributes>\
				<clef>\
					<sign>C</sign>\
					<line>2</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="12">\
			<attributes>\
				<clef>\
					<sign>C</sign>\
					<line>1</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="13">\
			<attributes>\
				<clef>\
					<sign>percussion</sign>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="14">\
			<attributes>\
				<clef>\
					<sign>G</sign>\
					<line>2</line>\
					<clef-octave-change>1</clef-octave-change>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="15">\
			<attributes>\
				<clef>\
					<sign>F</sign>\
					<line>4</line>\
					<clef-octave-change>1</clef-octave-change>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="16">\
			<attributes>\
				<clef>\
					<sign>TAB</sign>\
					<line>5</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="17">\
			<attributes>\
				<clef>\
					<sign>none</sign>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="18">\
			<attributes>\
				<clef>\
					<sign>G</sign>\
					<line>2</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>4</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
			<barline location="right">\
				<bar-style>light-heavy</bar-style>\
			</barline>\
		</measure>\
	</part>\
	<!--\
=========================================================\
-->\
	<part id="P2">\
		<measure number="1">\
			<attributes>\
				<divisions>64</divisions>\
				<key>\
					<fifths>0</fifths>\
					<mode>major</mode>\
				</key>\
				<time>\
					<beats>16</beats>\
					<beat-type>4</beat-type>\
				</time>\
				<clef>\
					<sign>G</sign>\
					<line>2</line>\
				</clef>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>1024</duration>\
				<voice>1</voice>\
				<type>long</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="2">\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>512</duration>\
				<voice>1</voice>\
				<type>breve</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>256</duration>\
				<voice>1</voice>\
				<type>whole</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>128</duration>\
				<voice>1</voice>\
				<type>half</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>64</duration>\
				<voice>1</voice>\
				<type>quarter</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>32</duration>\
				<voice>1</voice>\
				<type>eighth</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>16</duration>\
				<voice>1</voice>\
				<type>16th</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>8</duration>\
				<voice>1</voice>\
				<type>32nd</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>4</duration>\
				<voice>1</voice>\
				<type>64th</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>2</duration>\
				<voice>1</voice>\
				<type>128th</type>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>2</duration>\
				<voice>1</voice>\
				<type>128th</type>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="4">\
			<attributes>\
				<time>\
					<beats>24</beats>\
					<beat-type>4</beat-type>\
				</time>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>1536</duration>\
				<voice>1</voice>\
				<type>long</type>\
				<dot/>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="5">\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>768</duration>\
				<voice>1</voice>\
				<type>breve</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>384</duration>\
				<voice>1</voice>\
				<type>whole</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>192</duration>\
				<voice>1</voice>\
				<type>half</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>96</duration>\
				<voice>1</voice>\
				<type>quarter</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>48</duration>\
				<voice>1</voice>\
				<type>eighth</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>24</duration>\
				<voice>1</voice>\
				<type>16th</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>12</duration>\
				<voice>1</voice>\
				<type>32nd</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>6</duration>\
				<voice>1</voice>\
				<type>64th</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>3</duration>\
				<voice>1</voice>\
				<type>128th</type>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>3</duration>\
				<voice>1</voice>\
				<type>128th</type>\
				<dot/>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="6">\
			<attributes>\
				<time>\
					<beats>28</beats>\
					<beat-type>4</beat-type>\
				</time>\
			</attributes>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>1792</duration>\
				<voice>1</voice>\
				<type>long</type>\
				<dot/>\
				<dot/>\
			</note>\
		</measure>\
		<!--\
=======================================================\
-->\
		<measure number="7">\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>896</duration>\
				<voice>1</voice>\
				<type>breve</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>448</duration>\
				<voice>1</voice>\
				<type>whole</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>224</duration>\
				<voice>1</voice>\
				<type>half</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>112</duration>\
				<voice>1</voice>\
				<type>quarter</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>56</duration>\
				<voice>1</voice>\
				<type>eighth</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>28</duration>\
				<voice>1</voice>\
				<type>16th</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>14</duration>\
				<voice>1</voice>\
				<type>32nd</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>7</duration>\
				<voice>1</voice>\
				<type>64th</type>\
				<dot/>\
				<dot/>\
			</note>\
			<note>\
				<pitch>\
					<step>C</step>\
					<octave>5</octave>\
				</pitch>\
				<duration>7</duration>\
				<voice>1</voice>\
				<type>64th</type>\
				<dot/>\
				<dot/>\
			</note>\
			<barline location="right">\
				<bar-style>light-heavy</bar-style>\
			</barline>\
		</measure>\
	</part>\
</score-partwise>\
';